version: '3.3'

services:
  role:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: role
    entrypoint: ['/bin/sh', '-c', './entrypoint.sh']
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8084:8084
    networks:
      - capju
    env_file:
      - .env

networks:
  capju:
    external: true
